# Generated by Django 3.2.6 on 2022-10-01 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficy', models.CharField(max_length=50)),
                ('gravity', models.CharField(max_length=50)),
                ('distance_from_sun', models.CharField(max_length=50)),
                ('duration_of_day', models.CharField(max_length=50)),
                ('mass', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Moon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mars.mars')),
            ],
        ),
    ]
