# Generated by Django 3.2.6 on 2022-10-01 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moon',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moons', to='mars.mars'),
        ),
    ]
