# Generated by Django 3.2.6 on 2022-10-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='wrong_answer',
            new_name='wrong_answer_one',
        ),
        migrations.AddField(
            model_name='question',
            name='wrong_answer_two',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questi', to='quiz.answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
