# Generated by Django 3.2.6 on 2022-10-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20221001_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
    ]
